FROM python:3.12.0

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY src src

WORKDIR src/celery
CMD celery -A tasks worker --loglevel=INFO --concurrency=1
